name: ${project.name}
author: LucasEmanuel
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.Main

permissions:
  raygun.craft:
    description: Allows a player to craft the raygun.
    default: op